### ISSUE TITLE
关于导出html 源文件的问题

### ISSUE THREAD

**Issue by bujidao** [ronliruonan/aya-draglayout#1]
怎么才能导出当前样式的html 源文件？？如果只是单纯的页面拖拽布局，不能保存的话，貌似没有实际的用途

**Comment by ronliruonan** [comment]
当前的源文件，之前确实没有考虑到。

这边是将布局和组件名称，以json格式进行保存。这样就不用顾虑组件自身行为了

**Comment by ronliruonan** [comment]
@bujidao 请问是否解决了您的问题，我将关闭这个issue
