### ISSUE TITLE
你好，可以知道你的联系方式吗？

### ISSUE THREAD

**Issue by wgying** [ronliruonan/aya-draglayout#2]
我的QQ29554895

**Comment by ronliruonan** [comment]
谢谢！liruonan@hotmail.com

**Comment by wgying** [comment]
你好，我QQ29554895



---原始邮件---
发件人: "Ronan"<notifications@github.com&gt;
发送时间: 2020年12月26日(周六) 下午3:41
收件人: "ronliruonan/aya-draglayout"<aya-draglayout@noreply.github.com&gt;;
抄送: "wgying"<29554895@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ronliruonan/aya-draglayout] 你好，可以知道你的联系方式吗？ (#2)




 
谢谢！liruonan@hotmail.com
